### ISSUE TITLE
Release Gradle Plugin

### ISSUE THREAD

**Issue by dodie** [dodie/scott#51]
## Prerequisites
- [x] Release Maven Artifacts for the next version.

## Tasks
- [x] Release the Scott Gradle Plugin to the [Plugin Portal](https://guides.gradle.org/publishing-plugins-to-gradle-plugin-portal/). (See #44.)
- [x] Check and update user guides. Make a note on how to release the whole suite.

**Comment by dodie** [comment]
The plugin is released to the Plugin Portal and now waiting for approval. Once it's approved, the docs should be updated to promote the Gradle plugin instead of Maven.
